name: Release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Authenticate npm
      run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Deploy
      run: npm run publish

    - name: Publish to GitHub Packages
      run: npm publish --registry=https://npm.pkg.github.com
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            dist/**
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}