name: Release

on:
  push:
    # Trigger the workflow when a tag matching semantic versioning is pushed
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Build Package
        run: npm run build

      - name: Run Tests
        run: npm test

      - name: Publish Package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Configure npm for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > ~/.npmrc
          # Optionally, you can also specify a scope if your package uses one:
          # echo "@OWNER:registry=https://npm.pkg.github.com" >> ~/.npmrc

      - name: Publish Package to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changelog or details about this release.
